version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: binary-mlops-api
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - MLFLOW_TRACKING_URI=file:/app/mlruns
    volumes:
      # ðŸ”‘ trained model artifacts
      - ./models:/app/models

      # ðŸ”‘ mlflow runs
      - ./mlruns:/app/mlruns
    restart: unless-stopped

  dashboard:
    build:
      context: .
      dockerfile: Dockerfile.dashboard
    container_name: binary-mlops-dashboard
    ports:
      - "8501:8501"
    environment:
      - PYTHONPATH=/app
      - MLFLOW_TRACKING_URI=file:/app/mlruns
    volumes:
      # ðŸ”‘ dashboard must read same model
      - ./models:/app/models

      # ðŸ”‘ mlflow UI consistency
      - ./mlruns:/app/mlruns
    depends_on:
      - api
    restart: unless-stopped
