services:
  api:
    volumes:
      - ./models:/app/models
      - ./artifacts:/app/artifacts
      - ./mlruns:/app/mlruns

  dashboard:
    volumes:
      - ./models:/app/models
      - ./artifacts:/app/artifacts
      - ./mlruns:/app/mlruns
