[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "binary-classification-mlops"
version = "0.1.0"
description = "Binary classification MLOps project"
requires-python = ">=3.11"

dependencies = [
  "pandas",
  "numpy",
  "scikit-learn",
  "joblib",
  "pyarrow",
  "mlflow",
  "optuna"
]

[project.optional-dependencies]
api = [
  "fastapi",
  "uvicorn[standard]"
]
dashboard = [
  "streamlit"
]

[tool.setuptools]
# This tells setuptools: treat ./src as the package root
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
